#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_I2C) += synaptics_dsx_i2c.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_SPI) += synaptics_dsx_spi.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_RMI_HID_I2C) += synaptics_dsx_rmi_hid_i2c.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_CORE) += synaptics_dsx_core.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_RMI_DEV) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_FW_UPDATE) += synaptics_dsx_fw_update.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_TEST_REPORTING) += synaptics_dsx_test_reporting.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_PROXIMITY) += synaptics_dsx_proximity.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_ACTIVE_PEN) += synaptics_dsx_active_pen.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_GESTURE) += synaptics_dsx_gesture.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_V589_VIDEO) += synaptics_dsx_video.o
