#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_I2C) += synaptics_btn_i2c.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_SPI) += synaptics_btn_spi.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_RMI_HID_I2C) += synaptics_btn_rmi_hid_i2c.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_CORE) += synaptics_btn_core.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_RMI_DEV) += synaptics_btn_rmi_dev.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_FW_UPDATE) += synaptics_btn_fw_update.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_TEST_REPORTING) += synaptics_btn_test_reporting.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_PROXIMITY) += synaptics_btn_proximity.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_ACTIVE_PEN) += synaptics_btn_active_pen.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_GESTURE) += synaptics_btn_gesture.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_VIDEO) += synaptics_btn_video.o
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_DEBUG) += synaptics_btn_debug.o
