obj-$(CONFIG_NUBIA_SENSORS_FP)                  += gf318m/
obj-$(CONFIG_NUBIA_SENSORS_FP)                  += fpc1020/
obj-$(CONFIG_NUBIA_SENSORS_FP)			+= gf3208/
obj-$(CONFIG_NUBIA_SENSORS_FP)			+= gf5216m/
obj-$(CONFIG_NUBIA_FP_AUTODETECT)		+= fp_autodetect.o

