#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_I2C) += btn_synaptics_i2c.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_SPI) += btn_synaptics_spi.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_RMI_HID_I2C) += btn_synaptics_rmi_hid_i2c.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_CORE) += btn_synaptics_core.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_RMI_DEV) += btn_synaptics_rmi_dev.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_FW_UPDATE) += btn_synaptics_fw_update.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_TEST_REPORTING) += btn_synaptics_test_reporting.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_PROXIMITY) += btn_synaptics_proximity.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_ACTIVE_PEN) += btn_synaptics_active_pen.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_GESTURE) += btn_synaptics_gesture.o
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302_VIDEO) += btn_synaptics_video.o
