obj-$(CONFIG_AL3200) += basic_setting_cmd.o
obj-$(CONFIG_AL3200) += bulk_data_cmd.o
obj-$(CONFIG_AL3200) += camera_profile_cmd.o
obj-$(CONFIG_AL3200) += ispctrl_if_master.o
obj-$(CONFIG_AL3200) += miniisp.o
obj-$(CONFIG_AL3200) += miniisp_ctrl.o
obj-$(CONFIG_AL3200) += operation_cmd.o
obj-$(CONFIG_AL3200) += sys_manage_cmd.o

