#
# Makefile for the nubia drivers.
#
obj-$(CONFIG_NUBIA_TYPEC)            += nubia_typec/
obj-$(CONFIG_NUBIA_TOUCHSCREENS)      += touch/
obj-$(CONFIG_NUBIA_NFC)     	+= nfc/
obj-$(CONFIG_NUBIA_FINGERPRINT)                    += fingerprint/
obj-$(CONFIG_NUBIA_LEDS)			+=leds/
obj-$(CONFIG_NUBIA_VIBRATOR)		+=vibrator/
obj-$(CONFIG_NUBIA_SENSORS)			+=sensors/

