#---------------------------PROX SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)			+= txc_pa224.o
obj-$(CONFIG_NUBIA_SENSORS_PROX_PA22X)			+= txc/
obj-$(CONFIG_NUBIA_SENSORS_ALS_PROX_ADSP9922)	+= apds9922/
#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)			+= rohm_bh1745.o
#---------------------------HALL SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE)			+= hall_device.o
#---------------------------PRESSURE_DEVICE ----------------------------#
obj-$(CONFIG_NUBIA_SENSORS_PRESSURE_DEVICE)		+= pressure_device_ndt.o
#--------------------------IR Remote------------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_IR_REMOTE_I_THREE)	+= i_three.o
#--------------------------IR Remote------------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_TMD2725)				+= tmd2725/

