#
#. Makefile for nubia typec chip driver select.
#
obj-$(CONFIG_NUBIA_TYPEC_FUSB301)	+= fusb301.o
obj-$(CONFIG_NUBIA_TYPEC_PTN5150)	+= ptn5150.o
obj-$(CONFIG_NUBIA_TYPEC_TUSB320)	+= tusb320.o
obj-$(CONFIG_NUBIA_TYPEC_PI5U)		+= pi5u.o
