#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_TOUCHSCREEN_SELECT_SYNAPTICS)      += synaptics_dsx/
obj-$(CONFIG_NUBIA_TOUCHSCREENS_SYNAPTICS_DSX) += nubia_synaptics_dsx/
obj-$(CONFIG_NUBIA_TOUCHSCREEN_CYPRESS_BUTTON) += cypress_button/
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_DSX_2_7_0) += synaptics_dsx_2.7.0/
obj-$(CONFIG_NUBIA_TOUCHSCREEN_SYNAPTICS_BTN_2_7_0) += synaptics_btn_2.7.0/
obj-$(CONFIG_NUBIA_TOUCHBUTTON_SYNAPTICS_S1302) += synaptics_s1302/